name: MCPACK

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - name: Extract commit ish
      shell: bash
      run: echo "##[set-output name=ish;]$(echo ${GITHUB_SHA::7})"
      id: extract_ish

    - name: Create .mcpack
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: pack.mcpack
        path: |
          textures/**
          LICENSE.md
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: unity-${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_ish.outputs.ish }}.${{ github.run_id }}
        path: pack.mcpack
